# This workflow will make a static code analysis using the codacy tool

name: Codacy Analysis

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  schedule:
  - cron: "0 0 * * 0"

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master

      - name: Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@master
        with:
          output: results.sarif
          format: sarif
          # Adjust severity of non-security issues
          gh-code-scanning-compat: true
          # Force 0 exit code to allow SARIF file generation
          # This will handover control about PR rejection to the GitHub side
          max-allowed-issues: 2147483647
      
      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: results.sarif
